#!/bin/sh
RED='\033[0;31m'
NC='\033[0m'

branch_name=$(git rev-parse --abbrev-ref HEAD)

# List of protected branches
PROTECTED_BRANCHES=("develop" "main")

if [[ " ${PROTECTED_BRANCHES[@]} " =~ " ${branch_name} " ]]; then
  echo -e "${RED}Pushing to '${branch_name}' is not allowed! Please create a merge request.${NC}"
  exit 1
fi

echo "Push is allowed, continuing..."