#!/bin/sh
RED='\033[0;31m'
NC='\033[0m'

branch_name=$(git rev-parse --abbrev-ref HEAD)

# Dùng chuỗi phân tách bằng khoảng trắng thay vì mảng
PROTECTED_BRANCHES=" develop main "

# Kiểm tra xem chuỗi PROTECTED_BRANCHES có chứa " branch_name " hay không
case "$PROTECTED_BRANCHES" in
*" $branch_name "*)
  echo -e "${RED}Pushing to '${branch_name}' is not allowed! Please create a merge request.${NC}"
  exit 1
  ;;
esac

echo "Push is allowed, continuing..."
